\documentclass[xcolor={dvipsnames}, handout]{beamer}

\usepackage{../assets/pres-template_MOW}

%--------------------------------------------------------------------------
% Specific to this document ---------------------------------------
%--------------------------------------------------------------------------
% \setbeamercovered{transparent}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\setlength{\tabcolsep}{1.3pt}
\title{Social Science Inquiry III}
\subtitle{Week 1: Introduction to science and social science of climate policy}
\date{Spring 2026}
\author{Molly Offer-Westort}
\institute{Department of Political Science, \\University of Chicago}


\begin{document}
\SweaveOpts{concordance=TRUE}

%-------------------------------------------------------------------------------%
\frame{\titlepage
\thispagestyle{empty}
}
%-------------------------------------------------------------------------------%
\begin{frame}{Reading papers}

What to get out of reading a research paper:
\begin{itemize}
\item What is the main question of the paper?\pause
\item What method do the authors use to address the question? \pause
For empirical papers:\pause
\begin{itemize}
\item Data (Where does it come from/how is it generated? What is the sample population? What is being measured?)\pause
\item Research design/strategy\pause
\item Statistical tools\pause
\end{itemize}
\item What is the answer that the authors get to the main question?
\end{itemize}

\pause
How would you answer these questions with the \cite{sparkman2022americans} paper?

\end{frame}


%%%%%NOTE%%%%%
\note{
\scriptsize \singlespacing

\begin{itemize}
\item xxxx
\end{itemize}

}

%-------------------------------------------------------------------------------%
\backupbegin
%-------------------------------------------------------------------------------%

\begin{frame}[allowframebreaks]{References}
    \bibliographystyle{apalike}
    \bibliography{../assets/bib}
\end{frame}
%-------------------------------------------------------------------------------%
\backupend
\end{document}
%
%-------------------------------------------------------------------------------%

%%% [[TEMPLATE]] %%%
\begin{frame}{Frametitle}

\begin{itemize}
\item xxx
\end{itemize}

\end{frame}


%%%%%NOTE%%%%%
\note{
\scriptsize \singlespacing

\begin{itemize}
\item xxxx
\end{itemize}

}

%-------------------------------------------------------------------------------%